// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzpom7q0i5GiRcpTAKy1HzULtLef16LOI',
    appId: '1:190891862632:web:02b5446c975579e94d29dd',
    messagingSenderId: '190891862632',
    projectId: 'tictactoe-e5481',
    authDomain: 'tictactoe-e5481.firebaseapp.com',
    storageBucket: 'tictactoe-e5481.appspot.com',
    measurementId: 'G-8W17BPX5RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHlujEe535CsVptANiIckWZweaVpBXo9A',
    appId: '1:190891862632:android:2cd46b43660cc26d4d29dd',
    messagingSenderId: '190891862632',
    projectId: 'tictactoe-e5481',
    storageBucket: 'tictactoe-e5481.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh8M0EIMUeZRIzF86p_6dAHAGkNyqHKdo',
    appId: '1:190891862632:ios:c9491f992b1ab06b4d29dd',
    messagingSenderId: '190891862632',
    projectId: 'tictactoe-e5481',
    storageBucket: 'tictactoe-e5481.appspot.com',
    iosBundleId: 'com.example.proje1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh8M0EIMUeZRIzF86p_6dAHAGkNyqHKdo',
    appId: '1:190891862632:ios:c9491f992b1ab06b4d29dd',
    messagingSenderId: '190891862632',
    projectId: 'tictactoe-e5481',
    storageBucket: 'tictactoe-e5481.appspot.com',
    iosBundleId: 'com.example.proje1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzpom7q0i5GiRcpTAKy1HzULtLef16LOI',
    appId: '1:190891862632:web:0eb6981b486aaf9c4d29dd',
    messagingSenderId: '190891862632',
    projectId: 'tictactoe-e5481',
    authDomain: 'tictactoe-e5481.firebaseapp.com',
    storageBucket: 'tictactoe-e5481.appspot.com',
    measurementId: 'G-7BT5DWE49B',
  );
}
